In [4]:
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *
from tkinter import *

# These lines do some fancy plotting magic.
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [5]:
IBM= 'Ability to look at things differently, debug, troubleshoot, design and implement solutions to complex technical issues. Strong technical and analytical abilities, a knack for driving impact and growth, and experience with a programming/scripting in a language such as Java or Python. Basic understanding of statistical programming in a language such as R, Python, or SAS, SPSS, MATLAB. Basic understanding of Cloud (AWS, Azure, etc.). Excellent verbal and written communication skills. Work or internship experience using data science tools in a corporate environment. Interest in, understanding of, or experience with Design Thinking and Agile Development Methodologies. Willingness to travel up to 100% of the time. Computer Science, Data Science, Applied Mathematics, Statistics, Cognitive Science, Artificial Intelligence, Business Intelligence, Operations Research, Engineering'
Reddit = 'Required Qualifications: Actively working towards a Bachelor’s, Master’s, or PhD degree in Computer Science, Data Science, Mathematics, Statistics, Physics, or related fields Graduating between Fall 2022 and Summer 2023 Exposure to SQL programming language Curious or driven by data analysis (strong analytical skills) A desire to work at Reddit HQ in San Francisco or New York City over Summer 2022 (Subject to change based on safety guidelines created due to the global pandemic) You’re over the age of 18 and authorized to work in the United States Preferred Qualifications: Working towards an advanced degree (Master’s or PhD) Strong SQL and Python knowledge Experience working at a small start up or mid-sized company'
Amazon = 'Basic qualifications Currently enrolled in or will receive a Bachelor’s in Computer Science, Computer Engineering,Information Management, Information Systems, or an equivalent technical discipline with a conferral date between September 2022 – August 2024 Experience with data mining and data transformation Experience with database and/or data warehouse solutions Experience building data pipelines or automated ETL processes Experience with SQL Experience with one or more scripting language (e.g., Python, KornShell) Preferred qualifications Enrolled in a Master’s Degree or advanced technical degree Previous technical internship(s), if applicable Can articulate the basic differences between datatypes (e.g. JSON/NoSQL, relational) Familiar with the basic implications of different implementation decisions (e.g., distributed processing, parallel processing) Understand the basics of designing and implementing a data schema (e.g., normalization, relational model vs dimensional model) Experience building code based on data pipelines able to process big datasets Knowledge of writing and optimizing SQL queries with large-scale, complex datasets Experience with big data processing technology (e.g., Hadoop or ApacheSpark), data warehouse technical architecture, infrastructure components, and reporting/analytic tools and environments Experience with data visualization software (e.g., AWS QuickSight or Tableau)'
Tata='Computer Engineering (CE), Computer Science (CS) or Software Engineering (SE), Information Technology, Information Systems, Management Information Systems, Math, Physics, Statistics Cumulative GPA of 3.0 or higher Knowledge of basic computer science concepts, programming, Information Systems. Knowledge of one programming language is a must (preferable Python) Strong Knowledge and experience of writing queries in SQL and query optimization Knowledge of statistics and basic data analytics concepts to derive information from data. Knowledge of machine learning algorithms and techniques is a plus. Strong analytical ability to collect data from different sources, analyze it and present it to stakeholders Exposure to BI tools, Data Visualization, ETL concepts and application. Interest and willingness to travel and relocation'
Two_sigma='You will take on the following responsibilities: Independently research and develop hypotheses based on diverse and unique real-world datasets Conduct literature reviews to develop and apply cutting-edge methodologies for extracting real-world signals from our vast data holdings. Partner with our engineers and business stakeholders to rigorously explore and test your theories All the while, you’ll remain engaged in the academic community. As examples, you can: Join our reading circles to stay up to date on the latest research papers in your fields Attend academic seminars to learn from thought leaders from top universities You should possess the following qualifications: Are pursuing a degree in a technical or quantitative discipline, like chemistry, computer science, economics, statistics, or quantitative social science, with approximately one year remaining in your programs (all levels welcome, from bachelor’s to doctorate) Proficient in Python and SQL Performed an in-depth research project, examining real-world data Are an independent thinker who can creatively approach data analysis and communicate complex ideas clearly You don’t need a background in finance. It’s nice to have, but more than half of Two Sigma’s employees come from outside the finance industry. If you’ve got the research skills, we can teach you the financial aspects of the job.'
Infosys='Qualifications Basic At least or In pursuit of a 4- year Bachelor’s degree required from an accredited institution with degree completed upon joining. U.S. citizens and those authorized to work in the U.S. are encouraged to apply. We are unable to sponsor at this time. Positions are across multiple locations within USA. Candidate must be located within commuting distance or be willing to relocate to the area of work. This position may require travel and/ or relocation. Preferred Domain understanding in generic areas e.g. Finance, Telecom, etc. Good client interaction skills and communication skills. Planning and co-ordination skills. Software Development/ Programming - Knowledge of how to develop code and document artifacts including unit test plans and ensure that the output is as per the given specifications and SLAs. Testing - Perform testing activities (Functional, Integration, System, User experience) based on the plans and in line with defined processes with guidance from supervisor. Production Support - Respond to the issues assigned, conduct analysis, suggest / implement workarounds, communicate to all the stakeholders and close issues as per the agreed timelines Knowledge Management activities including documentation and knowledge gathering of the modules he/she is working on. A recent graduate or currently in pursuit of the degree. Willingness to relocate anywhere within the US.'
Microsoft='Minimum of a bachelor’s degree with 2+ years of relevant experience in investment banking, strategy, or consulting. Preferred Qualifications A good understanding of financial and business analysis, unit economics and valuation modeling using multiple methods. Knowledge of sector and market analysis; ideally has performed market competitive and consulting presentations and studies Demonstrated passion for Technology, Venture Capital, Start-ups, and entrepreneurship Critical thinking, including superior research and analytical abilities Excellent writing, presentation, and verbal communication skills Experience managing multiple projects under compressed timeframes Ability to develop creative insights, recommendations, and solutions Ability to influence internal and external audiences, stakeholders using evangelism, partnership, and networking skills Demonstrated experience achieving results through collaboration in a strong team-centered environment Willingness to work at times under time pressure due to competitive deal situations and short investment timescales Extremely positive, open, and flexible, intellectually curious with good listening skills, detail-oriented and a self-starter who enjoys working in a collegial workplace. Mental flexibility to be able to adapt to multiple audiences/cultures'
Linkedin='BA/BS degree in engineering, math, statistics, physics, computer science, business or related discipline 2+ years of work experience in a strategy related role with an emphasis on quantitative skills Preferred Qualifications: Background in management consulting, investment banking, private equity, strategy or an operational or growth role within a technology company Proactive and passionate: You’re independently capable of seeking information, solving conceptual problems, corralling resources, and delivering results in challenging situations High-energy, team-first attitude: You’re motivated to work collaboratively in a fast-paced, ever-changing environment to help our growing business Highly analytical: You’re analytical, with experience decomposing and solving real world business problems, ideally building/using advanced models. SQL a plus. Concise and effective communications: You’re able to articulately present and debate recommendations with cross-functional teams and senior leadership'
Apple='Experience in designed data structures and models for a data lake and cloud data warehouses supporting downstream applications based on Tableau, Filemaker and other BI tools Strong knowledge of ETL processes, relational database principles; working experience in Tableau Prep, or synthesizing decentralized data sets Experience in developing within FileMaker Pro or programming languages such as SQL, Python or R. Description Lead deep dive analysis, segmentation and slicing and dicing of operations, financial, and manufacturing data to distill actionable insights for the team. The valuable insights will drive conversations and make an impact to Apple’s manufacturing strategy and costs. Produce reports & maintain KPI dashboards to monitor the performance of our aggregate non-Materials spend across development & manufacturing costs, internal costs, and other key contributors to the cost of manufacturing. Build business cases for process enhancements within the organization to enable the team to run efficiently, effectively, and with a high degree of accuracy. You will develop, optimize and oversee conceptual and logical data architecture and integrations across multiple internal and external products. The ideal candidate will have proven expertise in data analysis, data modeling and data engineering with significant experience advocating solutions in cloud-native data management platforms.'
Tesla= 'Currently pursuing an undergrad or master’s degree in engineering, Computer Science, Business, and/or other quantitative and technical field. Evidence of exceptional ability, especially within an ambiguous environment 2-5 years of experience in analytics, program manager, or other structured training program Demonstrated success driving tangible impact / influencing within a broader organization Ability to quickly grasp technical concepts at a detailed level, and synthesize implications Strong written and verbal communication skills, particularly with senior business leadership Proficient with SQL, Python, Excel VBA and Tableau or similar dashboarding tool Experience with JIRA and git Highly collaborative, team oriented, and comfortable leading cross-functional projects, especially those consisting of both technical and non-technical stakeholdersA passion for sustainable energy'

In [6]:
type(IBM)

str

In [7]:
#Converting List to string
def listToString(s): 
    str1 = "" 
    for ele in s: 
        str1 += ele  
    return str1

In [8]:
#Changing the Table into array
def converter(sample):
    array=make_array()
    array=sample.split(',')
    listToString(array)
    array=sample.split('.')
    listToString(array)
    array=sample.split(' ')
    listToString(array)
    return array

In [9]:
def removing_process(a, column_of_the_table):
    a = a.where(column_of_the_table, are.not_equal_to('the'))
    a = a.where(column_of_the_table, are.not_equal_to('a'))
    a = a.where(column_of_the_table, are.not_equal_to('that'))
    a= a.where(column_of_the_table, are.not_equal_to('and'))
    a= a.where(column_of_the_table, are.not_equal_to('or'))
    a = a.where(column_of_the_table, are.not_equal_to('in'))
    a= a.where(column_of_the_table, are.not_equal_to('of'))
    a= a.where(column_of_the_table, are.not_equal_to('as'))
    a= a.where(column_of_the_table, are.not_equal_to('with'))
    a= a.where(column_of_the_table, are.not_equal_to('such'))
    a= a.where(column_of_the_table, are.not_equal_to('as'))
    a= a.where(column_of_the_table, are.not_equal_to('to'))
    a= a.where(column_of_the_table, are.not_equal_to('and'))
    a= a.where(column_of_the_table, are.not_equal_to('at'))
    a= a.where(column_of_the_table, are.not_equal_to('2022'))
    a= a.where(column_of_the_table, are.not_equal_to('are'))
    a= a.where(column_of_the_table, are.not_equal_to('within'))
    a= a.where(column_of_the_table, are.not_equal_to('is'))
    a= a.where(column_of_the_table, are.not_equal_to('be'))
    a= a.where(column_of_the_table, are.not_equal_to('from'))
    a= a.where(column_of_the_table, are.not_equal_to('-')) 
    a= a.where(column_of_the_table, are.not_equal_to('Are')) 
    a= a.where(column_of_the_table, are.not_equal_to('on')) 
    a= a.where(column_of_the_table, are.not_equal_to('our')) 
    a= a.where(column_of_the_table, are.not_equal_to('it')) 
    a= a.where(column_of_the_table, are.not_equal_to('You')) 
    a= a.where(column_of_the_table, are.not_equal_to('an')) 
    a= a.where(column_of_the_table, are.not_equal_to('can')) 
    a= a.where(column_of_the_table, are.not_equal_to('(e.g.,')) 
    a= a.where(column_of_the_table, are.not_equal_to('you')) 
    a= a.where(column_of_the_table, are.not_equal_to('your')) 
    a= a.where(column_of_the_table, are.not_equal_to('(all')) 
    a= a.where(column_of_the_table, are.not_equal_to('All')) 
    a= a.where(column_of_the_table, are.not_equal_to('over')) 
    a= a.where(column_of_the_table, are.not_equal_to('per')) 
    a= a.where(column_of_the_table, are.not_equal_to("(Master’s")) 
    a= a.where(column_of_the_table, are.not_equal_to("As")) 
    a= a.where(column_of_the_table, are.not_equal_to("Qualifications:")) 
    a= a.where(column_of_the_table, are.not_equal_to("A")) 
    a= a.where(column_of_the_table, are.not_equal_to("Bachelor’s")) 
    a= a.where(column_of_the_table, are.not_equal_to("You’re")) 
    a= a.where(column_of_the_table, are.not_equal_to("will")) 
    return a

In [10]:
#ALL IN ONE
main=0
def change_table(company_name,main):
    main =Table().with_column(company_name, converter(main))
    main = main.group(company_name).sort('count',descending=True)
    main = removing_process(main, company_name)
    main = main.take(np.arange(0,40))
    return main

In [11]:
a= change_table('Amazon',Amazon).take(np.arange(0,40)).column('Amazon')
b= change_table('IBM',IBM).take(np.arange(0,40)).column('IBM')
c= change_table('reddit',Reddit).take(np.arange(0,40)).column('reddit')
d= change_table('Tata',Tata).take(np.arange(0,40)).column('Tata')
e= change_table('Two_sigma',Two_sigma).take(np.arange(0,40)).column('Two_sigma')
f= change_table('Infosys',Infosys).take(np.arange(0,40)).column('Infosys')
g= change_table('Microsoft',Microsoft).take(np.arange(0,40)).column('Microsoft')
h= change_table('Linkedin',Linkedin).take(np.arange(0,40)).column('Linkedin')
i= change_table('Apple',Apple).take(np.arange(0,40)).column('Apple')
j= change_table('Tesla',Tesla).take(np.arange(0,40)).column('Tesla')
#a.with_column('IBM',b).with_column('reddit', c).with_column('Tata', d).with_column('Two_sigma',e).with_column('Infosys',f)
da= np.append(a,b)
da= np.append(da,c)
da= np.append(da,d)
da= np.append(da,e)
da= np.append(da,f)
da= np.append(da,g)
da= np.append(da,h)
Table().with_columns('group',np.append(da,i)).group('group').sort('count',descending=True).show()

In [12]:
change_table('Apple',Apple).show()